# Generated by Django 3.0.8 on 2020-07-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam iure eius excepturi at explicabo officia illum illo doloremque eligendi dolor? Sit assumenda neque optio atque, perspiciatis maiores cum expedita nostrum impedit unde quidem.'),
        ),
    ]
